//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace LiverpoolAjax.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class EmployeeTbl
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Office { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Image { get; set; }

		[NotMapped]
		public HttpPostedFileBase ImageUpload { get; set; }

		public EmployeeTbl()
		{
			Image = "~/AppFiles/Images/DefaultPerson.png";
		}
	}
}
